Repository c-h-w-h/cds, pull requests merged in 2023-04, with the labels that each got.

#88 Docs/story description: 컴포넌트 스토리 타입 정리 및 설명 추가
  .storybook/preview.jsx
  src/components/@layout/Center/Center.stories.tsx
  src/components/@layout/Container/Container.stories.tsx
  src/components/@layout/Flexbox/Flexbox.stories.tsx
  src/components/@layout/List/List.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Image/Image.stories.tsx
  src/components/RangeSelector/RangeSelector.stories.tsx
  src/components/Spacing/Spacing.stories.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Table/Table.stories.tsx
  src/components/Tabs/Tabs.stories.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/Typography/Typography.stories.tsx
Labels: 📖 docs

#92 fix: Thumb 위치 수정
  src/components/RangeSelector/index.tsx
Labels: 🧑‍🔧 refactor, 🛠 fix

#85 Feat/select: Select 컴포넌트 접근성 및 OptGroup 추가
  src/components/Dropdown/index.tsx
  src/components/Select/Select.stories.tsx
  src/components/Select/index.tsx
  src/components/Select/useSelect.tsx
  src/components/Typography/index.tsx
  src/constants/key.ts
  src/utils/getNextElement.ts
Labels: 🧑‍🔧 refactor, ✨ feat

#105 Docs/readme: README.md 작성
  .prettierrc
  README.md
Labels: 📖 docs

#95 refactor: Story 및 React Template 수정
  templates/Component.tsx.hbs
  templates/Story.tsx.hbs
Labels: 🧑‍🔧 refactor, ⚙️ config

#110 Feat/icon: Icon 컴포넌트 deprecate 및 디자인 시스템 아이콘 추가
  src/components/Icon/CdsBag.tsx
  src/components/Icon/CdsHamburger.tsx
  src/components/Icon/CdsHeart.tsx
  src/components/Icon/CdsHome.tsx
  src/components/Icon/CdsSearch.tsx
  src/components/Icon/CdsUser.tsx
  src/components/Icon/Icon.stories.tsx
  src/components/Icon/common.ts
  src/components/Icon/index.tsx
  src/index.ts
Labels: ✨ feat

#103 Feat/input: Input 컴포넌트 리팩토링
  src/components/Input/Input.stories.tsx
  src/components/Input/index.tsx
Labels: 🧑‍🔧 refactor

#109 Feat/drawer: Drawer 컴포넌트 구현
  src/components/@common/CdsProvider/index.tsx
  src/components/@common/Portal/index.tsx
  src/components/@layout/MobileContainer/index.tsx
  src/components/Drawer/Drawer.stories.tsx
  src/components/Drawer/index.tsx
  src/components/Drawer/useDrawerStyle.tsx
  src/components/Dropdown/index.tsx
  src/components/Modal/index.tsx
  src/components/Toast/index.tsx
  src/constants/color.ts
  src/constants/portal.ts
  src/index.ts
  src/styles/dimmed.ts
  src/utils/index.ts
  src/utils/types/ChildProps.ts
  src/utils/types/SetState.ts
  tsconfig.path.json
Labels: ✨ feat

#102 Refactor/stories Storybook Docs 수정 작업
  .storybook/preview.jsx
  src/components/@layout/Center/Center.stories.tsx
  src/components/@layout/Container/Container.stories.tsx
  src/components/@layout/Flexbox/Flexbox.stories.tsx
  src/components/@layout/List/List.stories.tsx
  src/components/Carousel/Carousel.stories.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Image/Image.stories.tsx
  src/components/RangeSelector/RangeSelector.stories.tsx
  src/components/Spacing/Spacing.stories.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Table/Table.stories.tsx
  src/components/Tabs/Tabs.stories.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/Typography/Typography.stories.tsx
Labels: 📖 docs, 🧑‍🔧 refactor

#113 Refactor: Show Code 수정
  src/components/@layout/Center/Center.stories.tsx
  src/components/@layout/Container/Container.stories.tsx
  src/components/@layout/Flexbox/Flexbox.stories.tsx
  src/components/@layout/List/List.stories.tsx
  src/components/Carousel/index.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/index.tsx
  src/components/Image/Image.stories.tsx
  src/components/Select/Select.stories.tsx
  src/components/Select/index.tsx
  src/components/Spacing/Spacing.stories.tsx
  src/components/Table/Table.stories.tsx
  src/components/Toast/Toast.stories.tsx
Labels: 🧑‍🔧 refactor

#108 Feat/slider Slider 컴포넌트 구현
  src/components/RangeSelector/RangeSelector.stories.tsx
  src/components/RangeSelector/index.tsx
  src/components/Slider/Slider.stories.tsx
  src/components/Slider/index.tsx
  src/components/Slider/useSlider.ts
  src/constants/key.ts
  src/index.ts
Labels: ✨ feat

#114 Refactor/tabs Tabs 컴포넌트 수정사항 반영
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/index.tsx
  src/components/Tabs/useTriggerStyle.ts
  src/constants/key.ts
Labels: 🧑‍🔧 refactor

#98 Refactor/button: Button 컴포넌트 리팩토링
  src/@types/index.d.ts
  src/@types/variant.d.ts
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/Button/useButtonStyle.tsx
  src/components/Drawer/Drawer.stories.tsx
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Input/Input.stories.tsx
  src/components/Link/index.tsx
  src/components/Modal/Modal.stories.tsx
  src/components/Select/Select.stories.tsx
  src/components/Slider/Slider.stories.tsx
  src/components/Toast/Toast.stories.tsx
  src/components/Typography/index.tsx
  src/index.ts
Labels: 🧑‍🔧 refactor, 😱 help wanted

#117 Config/deploy: @chwh/cds 1.0.0 배포
  README.md
  package.json
  src/components/Badge/Badge.stories.tsx
  src/components/Carousel/index.tsx
  src/components/Drawer/index.tsx
  src/components/Drawer/useDrawerStyle.tsx
  src/components/Icon/index.tsx
  src/components/Input/Input.stories.tsx
  src/components/Input/index.tsx
  src/components/Select/index.tsx
  src/components/Table/index.tsx
  src/constants/color.ts
  src/constants/toast.ts
  src/utils/get-next-element.ts
  src/utils/index.ts
  src/utils/pixel-to-rem.ts
Labels: ⚙️ config

#119 Feat/theme-color: Theme color 변경 기능 구현
  README.md
  package.json
  src/@types/emotion.d.ts
  src/components/@common/CdsProvider/index.tsx
  src/components/@common/CdsProvider/theme.ts
  src/components/RadioButton/RadioButton.stories.tsx
  src/components/Slider/index.tsx
  src/components/Toast/ToastCore.tsx
  src/constants/color.ts
  src/styles/dimmed.ts
Labels: ✨ feat
