Repository c-h-w-h/cds, pull requests merged in 2023-03, with the labels that each got.

#32 Feat/modal: Modal 컴포넌트 구현
  src/components/Modal/Modal.stories.tsx
  src/components/Modal/index.tsx
Labels: ✨ feat

#39 Build/ci: 기본 CI action 추가
  .github/workflows/build-test.yml
  src/components/Image/index.tsx
Labels: ⚙️ config

#35 Refactor/table: Table 리팩토링 (export default, pixelToRem)
  src/components/Table/Table.stories.tsx
  src/components/Table/index.tsx
Labels: 🧑‍🔧 refactor

#41 Feat/chromatic : Chromatic 설치 및 CI 적용
  .github/workflows/chromatic.yml
  package.json
  src/components/Image/Image.stories.tsx
  yarn.lock
Labels: ⚙️ config

#50 Refactor/enum-types: enum 기반 타입 string literal로 변경
  src/@types/variant.d.ts
  src/components/Image/index.tsx
  src/components/Spinner/index.tsx
  src/components/Typography/index.tsx
  src/constants/image.ts
  src/constants/spinner.ts
  src/constants/typography.ts
  tsconfig.path.json
Labels: 🧑‍🔧 refactor

#44 Fix/defaultprops: DefaultProps에서 css 프로퍼티 제거
  src/components/@layout/Container/Container.stories.tsx
  src/components/@layout/Container/index.tsx
  src/components/@layout/Flexbox/Flexbox.stories.tsx
  src/components/@layout/Flexbox/index.tsx
  src/utils/types/DefaultProps.ts
Labels: 🛠 fix

#51 Feat/typography: color props 및 Highlight 컴포넌트 추가
  src/components/Typography/Highlight.tsx
  src/components/Typography/Typography.stories.tsx
  src/components/Typography/index.tsx
Labels: ✨ feat

#47 Feat/button: Button 컴포넌트 구현
  src/components/@layout/Flexbox/index.tsx
  src/components/Button/Button.stories.tsx
  src/components/Button/index.tsx
  src/components/Icon/index.tsx
  src/styles/.gitkeep
  src/styles/flex-box.ts
  src/utils/pixelToRem.ts
Labels: ✨ feat

#52 Fix: Typography color default value inherit으로 변경
  src/components/Button/index.tsx
  src/components/Typography/Typography.stories.tsx
  src/components/Typography/index.tsx
Labels: 🛠 fix

#48 Feat/input: Input 컴포넌트 구현
  src/components/Input/Input.stories.tsx
  src/components/Input/index.tsx
Labels: ✨ feat

#61 Refactor/dropdown: Dropdown 컴포넌트 리팩토링
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/index.tsx
Labels: 🧑‍🔧 refactor

#57 Feat/rangeSelector : RangeSelector 컴포넌트 구현
  src/components/RangeSelector/RangeSelector.stories.tsx
  src/components/RangeSelector/index.tsx
Labels: ✨ feat

#59 Feat/spacing: Spacing 컴포넌트 구현
  src/@types/variant.d.ts
  src/components/Spacing/Spacing.stories.tsx
  src/components/Spacing/index.tsx
  src/constants/spacing.ts
Labels: ✨ feat

#63 Feat/tabs: Tabs 컴포넌트 구현
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/index.tsx
Labels: ✨ feat

#65 Feat/select: Select 컴포넌트 구현
  src/components/Dropdown/index.tsx
  src/components/Select/Select.stories.tsx
  src/components/Select/index.tsx
  src/components/Select/useSelect.tsx
  src/styles/flex-box.ts
  src/utils/types/ChildrenProps.ts
  src/utils/types/DefaultProps.ts
  src/utils/types/DefaultPropsWithChildren.ts
Labels: ✨ feat

#67 Feat/tabs accessibility : 접근성 속성 및 키보드 이벤트 추가
  src/components/Tabs/Tabs.stories.tsx
  src/components/Tabs/index.tsx
  src/constants/key.ts
Labels: ✨ feat

#71 Refactor/dropdown: Dropdown 컴포넌트 리팩토링
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/index.tsx
Labels: 🧑‍🔧 refactor

#64 Feat/carousel: Carousel 컴포넌트 구현
  package.json
  src/@types/variant.d.ts
  src/components/Carousel/Carousel.stories.tsx
  src/components/Carousel/NavigationButton.tsx
  src/components/Carousel/index.tsx
  src/constants/carouselSlide.ts
Labels: ✨ feat

#81 Feat/use-safe-context: Context null check 공통 훅 추가
  src/components/Carousel/index.tsx
  src/components/Dropdown/index.tsx
  src/components/Select/index.tsx
  src/components/Tabs/index.tsx
  src/hooks/useSafeContext.tsx
Labels: ✨ feat

#73 Style/jsx-a11y: eslint 접근성 규칙 플러그인 추가
  .eslintrc
  package.json
  yarn.lock
Labels: 💇‍♂️ style

#75 Refactor/toast: Toast 커스텀 훅 정의 및 duration Props 추가
  src/components/Toast/Toast.stories.tsx
  src/components/Toast/index.tsx
  src/components/Toast/useToast.ts
  src/constants/color.ts
  src/constants/toast.ts
Labels: 🧑‍🔧 refactor, ✨ feat

#84 Config/component-cli: Plop.js를 이용한 CLI로 Component 파일 생성
  package.json
  plopfile.js
  templates/Component.tsx.hbs
  templates/Story.tsx.hbs
  yarn.lock
Labels: ⚙️ config
