Repository c-h-w-h/cds, pull requests merged in 2023-02, with the labels that each got.

#2 Feat/typography: Typography 컴포넌트 추가
  .eslintrc
  .storybook/main.cjs
  package.json
  src/components/.gitkeep
  src/components/Typography/Typography.stories.tsx
  src/components/Typography/index.tsx
  src/constants/typography.ts
  tsconfig.path.json
  vite.config.ts
  yarn.lock
Labels: ✨ feat

#4 Feat: Center 컴포넌트 구현
  src/components/Center/Center.stories.tsx
  src/components/Center/index.tsx
Labels: ✨ feat

#6 Feat: Badge 컴포넌트 구현
  package.json
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/index.tsx
  src/components/Typography/index.tsx
  yarn.lock
Labels: ✨ feat

#8 Style: stylelint 삭제
  .stylelintrc
  package.json
  yarn.lock
Labels: 💇‍♂️ style

#10 Feat/global: Global, CdsProvider 컴포넌트 추가
  .storybook/preview.cjs
  .storybook/preview.jsx
  src/@types/emotion.d.ts
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/index.tsx
  src/components/CdsProvider/index.tsx
  src/components/CdsProvider/theme.ts
  src/components/Global/index.tsx
  src/components/Typography/index.tsx
  src/constants/color.ts
  src/constants/typography.ts
  tsconfig.json
Labels: ✨ feat

#14 Feat/util-types: DefaultProps 유틸리티 타입 추가
  src/utils/types/DefaultProps.ts
  src/utils/types/DefaultPropsWithChildren.ts
  tsconfig.path.json
  vite.config.ts
Labels: ✨ feat

#20 Feat/util-types: DefaultProps에 optional children 추가
  src/utils/types/DefaultProps.ts
Labels: ✨ feat

#16 Feat/spinner: Spinner 컴포넌트 구현
  src/components/Spinner/Spinner.stories.tsx
  src/components/Spinner/index.tsx
  src/constants/spinner.ts
Labels: ✨ feat

#15 Feat/layout: Container, Flexbox, List 컴포넌트 구현
  src/components/Center/index.tsx
  src/components/Container/Container.stories.tsx
  src/components/Container/index.tsx
  src/components/Flexbox/Flexbox.stories.tsx
  src/components/Flexbox/index.tsx
  src/components/List/List.stories.tsx
  src/components/List/index.tsx
  src/utils/types/FlexContainerProps.ts
Labels: ✨ feat

#21 Style/convention: 기존 코드 코딩 컨벤션에 따라 수정
  .storybook/preview.jsx
  src/@types/emotion.d.ts
  src/components/@common/CdsProvider/index.tsx
  src/components/@common/CdsProvider/theme.ts
  src/components/@common/Global/index.tsx
  src/components/@layout/Center/Center.stories.tsx
  src/components/@layout/Center/index.tsx
  src/components/@layout/Container/Container.stories.tsx
  src/components/@layout/Container/index.tsx
  src/components/@layout/Flexbox/Flexbox.stories.tsx
  src/components/@layout/Flexbox/index.tsx
  src/components/@layout/List/List.stories.tsx
  src/components/@layout/List/index.tsx
  src/components/Badge/Badge.stories.tsx
  src/components/Badge/index.tsx
  src/components/Image/Image.stories.tsx
  src/components/Spinner/Spinner.stories.tsx
  src/components/Spinner/index.tsx
  src/components/Typography/index.tsx
  src/main.tsx
  tsconfig.path.json
  vite.config.ts
Labels: 💇‍♂️ style

#26 Feat/utils: pixelToRem 메서드 구현
  src/utils/pixelToRem.ts
Labels: ✨ feat

#27 Refactor/layout: Flexbox 컴포넌트 리팩토링
  src/components/@layout/Flexbox/Flexbox.stories.tsx
  src/components/@layout/Flexbox/index.tsx
  src/components/@layout/List/List.stories.tsx
  src/components/@layout/List/index.tsx
  src/utils/types/FlexContainerProps.ts
Labels: 🧑‍🔧 refactor

#29 Feat/table: Table 컴포넌트 구현
  src/components/Table/Table.stories.tsx
  src/components/Table/index.tsx
Labels: ✨ feat

#31 Feat/dropdown: Dropdown 컴포넌트 구현
  src/components/Dropdown/Dropdown.stories.tsx
  src/components/Dropdown/index.tsx
Labels: ✨ feat

#37 Fix/dropdown: Flexbox 수정사항 반영
  src/components/Dropdown/index.tsx
Labels: 🛠 fix
